#!/usr/bin/env python3
import sys

from agent import QLearning
from config import Config


def help() -> None:
    """Display help message and exit."""
    print("-visual on/off : Display the game or not (default : on)")
    print("-sessions <int> : Number of games to play (default : 1)")
    print("-load <file> : Load a Q-table model")
    print("-save <file> : Save the Q-table model")
    print("-dontlearn : Disable learning")
    print("-step-by-step : Wait for user input between each step")
    print("-help : Display this message")
    print("Example:")
    print("./snake -visual on -load models/100sess.csvtxt -sessions 10")
    sys.exit(0)


if __name__ == "__main__":
    # Parse command line arguments

    visual = True
    sessions = Config.EPISODES.value
    load = None
    save = None
    learn = True
    step_by_step = False
    i = 1
    while i < len(sys.argv):
        if sys.argv[i] == "-visual":
            visual = sys.argv[i+1] == "on"
            i += 1
        elif sys.argv[i] == "-sessions":
            sessions = int(sys.argv[i+1])
            i += 1
        elif sys.argv[i] == "-load":
            load = sys.argv[i+1]
            i += 1
        elif sys.argv[i] == "-save":
            save = sys.argv[i+1]
            i += 1
        elif sys.argv[i] == "-dontlearn":
            learn = False
        elif sys.argv[i] == "-step-by-step":
            step_by_step = True
        else:
            help()
        i += 1

    # Print configuration
    print("Visual:", visual)
    print("Sessions:", sessions)
    print("Load:", load)
    print("Save:", save)
    print("Learn:", learn)
    print("Step by step:", step_by_step)

    # Run the agent
    agent = QLearning(visual, sessions, step_by_step, learn)
    agent.load_model(load)
    agent.run()
    agent.save_model(save)
